### PR TITLE
Delay hash change during file export on iOS 13.x+

### LINKED ISSUE #382: LoginFile download partially broken on iOS 13+
iOS Safari 13 finally introduced support for the [download attribute](https://caniuse.com/#feat=download) such that on Safari 13+ our long tap download work-around is not used anymore.
Unfortunately the implementation of the download attribute seems to be broken or not compatible with our usage of it. Downloading the login file only succeeds sometimes and no pattern has been recognized so far when it works and when not.

So far two possible causes for that behavior have been identified but not investigated yet:
- The link with the download attribute gets set to `display: none` before the download concludes.
- iOS Safari might have problems downloading data urls. We could use an [object url](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) for a [blob](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob) instead.

### PR DESCRIPTION
**Pull request by nibhar**
While Safari on iOS 13 does support the download attribute, the resulting download prompt does not like the hash change  in the background happening in our setup. 
This PR changes that behaviour by delaying the hash change until after the prompt was confirmed.

This PR also increases core-web to Version 1.5.3.

Resolves #382

### CODE REVIEW

File: src/components/DownloadLoginFile.js [hunk 1]
```diff
@@ -166,8 +177,16 @@ class DownloadLoginFile extends Nimiq.Observable {
 
             // If window gets blurred, show 'Continue' button in interface and do not automatically
             // consider the download successful.
-            if (!document.hasFocus()) {
+            // As mobile Safari on iOS 13.x+ does support the download attribute, it no longer uses the long tap
+            // fallback. However, if the page changes its hash in the background while the promt asking to download
```
Comment (sisou) [inline src/components/DownloadLoginFile.js]: Typo `promt => prompt`

**Review by sisou — APPROVED** [review]
Perfect! I'll add the Nimiq lib hashes in a few minutes ;).

**Review by sisou — APPROVED** [review]

File: src/components/DownloadLoginFile.js [hunk 2]
```diff
@@ -42,7 +46,17 @@ class DownloadLoginFile extends Nimiq.Observable {
...
+            this._onDownloadEnd();
+            // Remove previously added classes after a short delay to restore the initial state.
+            window.setTimeout(() => {
+                this.$el.classList.remove('maybe-downloaded');
+                this.fire(DownloadLoginFile.Events.RESET);
+            }, 300);
+        });
+        $backToDownloadButton.addEventListener('click', () => {
+            this.$downloadButton.click();
+        });
```
Comment (danimoh) [inline src/components/DownloadLoginFile.js]: No need to open a block here.

File: src/components/DownloadLoginFile.js [hunk 3]
```diff
@@ -90,6 +105,9 @@ class DownloadLoginFile extends Nimiq.Observable {
         if (encryptedEntropy.byteLength !== KeyStore.ENCRYPTED_SECRET_SIZE) {
             throw new Errors.KeyguardError('Can only export encrypted Entropies');
         }
+        // Remove previously added classes to restore the initial state.
+        this.$el.classList.remove('maybe-downloaded');
+        this.fire(DownloadLoginFile.Events.RESET);
```
Comment (danimoh) [inline src/components/DownloadLoginFile.js]: You're using this twice. Might be worth moving this to a `reset` method.

File: src/components/DownloadLoginFile.js [hunk 4]
```diff
@@ -166,8 +184,16 @@ class DownloadLoginFile extends Nimiq.Observable {
...
             // consider the download successful.
-            if (!document.hasFocus()) {
+            // As mobile Safari on iOS 13.x+ does support the download attribute, it no longer uses the long tap
+            // fallback. However, if the page changes its hash in the background while the prompt asking to download
+            // the file was not confirmed yet, the download will simply do nothing. To prevent that behaviour the
+            // hash change is delayed by the .maybe-downloaded confirmation mechanism.
+            if (!document.hasFocus()
+                || (BrowserDetection.isIOS()
+                    && BrowserDetection.isSafari()
+                    && BrowserDetection.iOSVersion()[0] > 12)) {
```
Comment (danimoh) [inline src/components/DownloadLoginFile.js]: I think we should test whether we need to include iOS Chrome too.
Or didn't we even say we want to have the `Continue` button always on mobile?

**Review by danimoh — CHANGES_REQUESTED** [review]

File: src/components/DownloadLoginFile.js (hunk 4 above)
Comment (nibhar) [reply src/components/DownloadLoginFile.js]: Actually I think we should probably just get rid of the `BrowserDetection.isSafari()` condition.
For non iOS devices I think the continue button is simply not necessary, but on iOS 13 we can just declare this as default behaviour, no matter what browser.

**Review by danimoh — APPROVED** [review]
Resolves https://github.com/nimiq/keyguard/issues/382
